name: 'isomorphic_dart'
version: 0.0.1
description: >
  An absolute bare-bones web app.
#author: <your name> <email@example.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  appengine: any
  args: any
  browser: any
  frappe: any
  http: any
  redstone: any
  react: any
  shelf_appengine: any
  shelf_static: any
